### GET request to example server
GET http://localhost:3000/

###


### GET ALL BOOKS
GET http://localhost:3000/books
Content-Type: application/json

###


### PUT
PUT http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Władca Pierścieni",
  "author": "J.R.R. Tolkien",
  "category": "Fantasy"
}
###